# org.gradle.jvmargs=-Xmx4196M

# Minecraft & Fabric Dependencies
minecraft_version=26.2
yarn_mappings=26.2+build.1
loader_version=0.16.0
fabric_version=0.156.0+26.2

# Third-party Dependencies for Shading & Core Architecture
password4j_version=1.8.2
hikaricp_version=5.1.0
flyway_version=10.15.0
jedis_version=5.1.2
sqlite_version=3.46.0.0
postgresql_version=42.7.3
slf4j_version=2.0.13

# Mod Properties
mod_id=authsecured
mod_version=1.0.3
maven_group=net.authsecured
archives_base_name=authsecured
